services:
  logger-service:
    build: .
    container_name: logger-service
    user: root
    privileged: true
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - LOG_SCAN_INTERVAL_MS=${LOG_SCAN_INTERVAL_MS}
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "6030:6030"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f 'loggerservice.jar' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - plugins.security.disabled=${PLUGINS_SECURITY_DISABLED}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - OPENSEARCH_DASHBOARDS_PLUGINS_DISABLED=${OPENSEARCH_DASHBOARDS_PLUGINS_DISABLED}
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
      - OPENSEARCH_SSL_VERIFICATIONMODE=${OPENSEARCH_SSL_VERIFICATIONMODE}
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=${DISABLE_SECURITY_DASHBOARDS_PLUGIN}
      - OPENSEARCH_DASHBOARDS_I18N_LOCALE=${OPENSEARCH_DASHBOARDS_I18N_LOCALE}
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
